### ISSUE TITLE
Questions about autoware.universe end-to-end performance issues.

### ISSUE THREAD

**Issue by nainaigetuide** [tier4/CARET_analyze#203]
Hello.
- I'm doing work on profiling autoware.universe. At present, I have encountered the problem of high end-to-end delay, and I would like to ask you for advice.

        The machine configuration is as follows:
        Scenario: https://autowarefoundation.github.io/autoware-documentation/main/tutorials/ad-hoc-simulation/rosbag-replay-simulation/
        Environment
                OS: Ubuntu 20.04, 5.15.0-52-generic
                ROS: ROS2 Galactic
                CPU: Intel(R) Xeon(R) Silver 4114 CPU @ 2.20GHz 40 Core
                GPU: Tesla T4
                Memory: 64GByte
                Storage: 180GByte

- When using the Caret tool to analyze the delay, it is found that the delay is much higher than 100ms, and the bottleneck is not in the calculation of a certain ROS node. Every part seems to have a relatively high delay, such as attachments.

[test.pdf](https://github.com/tier4/CARET_report/files/10027128/test.pdf)

- When running autoware, the average CPU utilization rate is 40%, the highest load is 20, and the highest IO TPS is 190. These indicators do not show the bottleneck of the program.

- I have the following questions:

> Do you know the bottleneck that restricts the high latency of the system?

**Comment by takeshi-iwanari** [comment]
Hi,

End-to-end path in Autoware has [dropped message flows](https://tier4.github.io/CARET_doc/main/faq/#message-flow-looks-dropped) and [splited message flows](https://tier4.github.io/CARET_doc/main/faq/#message-flow-looks-split) because nodes run in various rates (e.g. 10Hz, 50Hz 30Hz, etc.) with phase differences.
The delay calculated by [chain_latency](https://tier4.github.io/CARET_doc/main/visualization/visualization_api/chain_latency/) includes delays for all of these message flows. Take the attached image for example, chain_latency considers L0 - L10 to calculate min,max,avg delays. That's the reason why the delay you analyzed using chain_latency becomes huge.
It's depends on what you want to analyze, but we recommend using [response_time](https://tier4.github.io/CARET_doc/main/faq/#how-response-time-is-calculated) to see end-to-end performance.
![image](https://user-images.githubusercontent.com/105265012/202360375-3083d5c5-5261-4357-bd78-9fd97d2c0a76.png)

**Comment by takam5f2** [comment]
@nainaigetuide  
Could you tell me if you want to keep this issue or not?

**Comment by nainaigetuide** [comment]
@takam5f2 @takeshi-iwanari thank you very much.
